version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/tomcat/webapps/ROOT
hooks:
  AfterInstall:
    - location: scripts/restart-tomcat.sh
      timeout: 60
      runas: ec2-user
